apiVersion: v1
kind: PersistentVolume
metadata:
  name: EBS
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4  
    volumeHandle: vol-018d7caeb112fc948  

