apiVersion: v1
kind: Service
metadata:
  name: nginx-np 
spec:
  type: Nodeport
  selecter:
    project : roboshop
    component: frontend
    environment: dev
  ports:
    protocol: TCP
    port: 80        #service port
    targerPort: 80  #container port  
